spring:
  main:
    banner-mode: off

  datasource:
    url: datasource.url
    username: datasource.username
    password: datasource.password

  jpa:
    show-sql: false
    hibernate:
      ddl-auto: none

  liquibase:
    change-log: classpath:/db/changelog/changelog-master.xml

app:

  server:
    url: ${app.server.url}

